# This is a basic workflow to help you get started with Actions

name: Tools Updater

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  schedule:
  - cron: "*/10 * * * *"

  push:
    branches:
    - 'master'
    ignore-paths:
    - '_data/devices.json'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Updation on Tools
      run: |
        python scripts/tools_updater.py update
        git add pb_tools.json
        git add PBRP/tools/*
        git commit -m "PBRP: Auto-Update Tools"
        git push -q https://${{ secrets.GITHUB_TOKEN }}@github.com/PitchBlackRecoveryProject/PitchBlackRecoveryProject.github.io master